logging:
  level:
    ROOT: INFO
    org.springframework: ERROR
    org.hibernate: ERROR
    com.kgisl.sb1: INFO

  pattern:
    console: "- %msg%n"
    file: "*[%-5p]-- %m--%n"
  file: 
    name: logs/sb1.log
server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:file:~/sb1
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true